apiVersion: v1
kind: Pod
metadata:
  name: cm3
spec:
  containers:
    - name: cm3-container
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: game-config
  restartPolicy: Never
