apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: anti
  name: anti
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: kind
              operator: In
              values:
              - special
          topologyKey: topology.kubernetes.io/zone
  containers:
  - image: busybox
    name: anti
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
