apiVersion: v1
kind: Pod
metadata:
  name: planet-pod
spec:
  containers:
    - name: planet-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/echo", "$(PLANET) $(MOON)" ]
      env:
        # Define the environment variable
        - name: PLANET
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: space
              # Specify the key associated with the value
              key: planet
        # Define the environment variable
        - name: MOON
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: space
              key: moon
              # Specify the key associated with the value
  restartPolicy: Never
