apiVersion: v1
kind: Pod
metadata:
  name: planet-pod
spec:
  containers:
    - name: planet-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "sleep 10" ]
      command: [ command: [ "/bin/echo", "$(PLANET) ]	
      env:
        # Define the environment variable
        - name: PLANET
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: planet
              # Specify the key associated with the value
              key: planet
  restartPolicy: Never
