apiVersion: v1
kind: Pod
metadata:
  name: kbsecret
spec:
  containers:
  - name: secret-container
    image: nginx
    volumeMounts:
    - name: foo
      mountPath: "/etc/admin-cred"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: usercreds
