apiVersion: v1
kind: Pod
metadata:
  name: space-system-pod
spec:
  containers:
    - name: space-system-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "ls /etc/system.conf/" ]
      volumeMounts:
      - name: space-system
        mountPath: /etc/system.conf
  volumes:
    - name: space-system
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: space-system
  restartPolicy: Never
